### ISSUE TITLE
[Chore] Research and setup Docker locally

### ISSUE THREAD

**Issue by vnntsu** [vnntsu/elixir-ic#5]
## Why

I can now run the server by mix, so I think it's worth researching Docker and running applications on it as well.
  - [x] Research Docker
  - [x] I'm able to run application on Docker

## Who Benefits?

Developers

**Comment by Nihisil** [comment]
Is it about only running the Elixir app inside Docker? Since the DB should be run inside Docker already, right?

**Comment by vnntsu** [comment]
@Nihisil yup, it is. Since we're using a template so this issue is only about researching and no code changes. But let's see if there are any problems, I will try to fix them.
