### ISSUE TITLE
[API] As a user, I can register a new account with email and password

### ISSUE THREAD

**Issue by vnntsu** [vnntsu/elixir-ic#8]
## Why

- Only authenticated users can interact with our application. Beforehand, they must register a new account.
- User can register by email and password.

## Acceptance Criteria

Add a new route and endpoint:
- endpoint: `/register`
- parameters: `email`, `password`
- JSON response:
  ```json
  TBD
  ```

**Comment by andyduong1920** [comment]
as Signup is an optional API, we can move that to the last sprint, what do you think @vnntsu

**Comment by vnntsu** [comment]
@andyduong1920 I agree, let me move it 👍
